# Generated by Django 4.1.1 on 2022-12-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phonenumber',
            field=models.IntegerField(default=0),
        ),
    ]
